### ISSUE TITLE
demo_output/penn_action-0104_AR25_60-100_fps5.mp4: No such file or directory

### ISSUE THREAD

**Issue by gauravkuppa** [jasonyzhang/phd#2]
Hello,

I am trying to run the following command:
`python demo.py --load_path models/phd.ckpt-199269 --vid_id 0104 --ar_length 25 --start_frame 60`

However, in the process of running, I get an error about a missing file or directory. I am not sure what is causing this or how to solve this bug.

`Rendering demo_output/penn_action-0104_AR25_60-100_fps5.mp4
0it [00:00, ?it/s]/home/gaurav/phd/src/util/render_utils.py:18: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if np.issubdtype(image.dtype, np.float):
38it [00:16,  2.37it/s]
ffmpeg -y -threads 16 -r 5 -i /tmp/tmp2p3lvrim/frame%08d.jpg -profile:v baseline -level 3.0 -c:v libx264 -pix_fmt yuv420p -an -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" demo_output/penn_action-0104_AR25_60-100_fps5.mp4
ffmpeg version n4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.1 (Arch Linux 9.2.1+20200130-2) 20200130
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, image2, from '/tmp/tmp2p3lvrim/frame%08d.jpg':
  Duration: 00:00:01.52, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 672x224 [SAR 100:100 DAR 3:1], 25 fps, 25 tbr, 25 tbn, 25 tbc
demo_output/penn_action-0104_AR25_60-100_fps5.mp4: No such file or directory
Removing /tmp/tmp2p3lvrim which contains 852.4KiB.`

Any assistance would be greatly appreciated. Thank you.

**Comment by jasonyzhang** [comment]
Hi,

Looks like the directory `demo_output` doesn't exist. Try making the folder before running the command.

Best,
Jason
